// packages/react/src/AuthContainer.tsx
'use client';

import type { AuthContainerProps } from './types';

/**
 * AuthContainer — Layout wrapper for authentication flows.
 *
 * Use `mode` to switch between credential-based, SSO-only, or combined layouts.
 */
export function AuthContainer({
  mode = 'credentials',
  title,
  description,
  children,
  className,
}: AuthContainerProps) {
  const classes = [
    'auth-container',
    mode !== 'credentials' && `auth-container--${mode}`,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes} role="group" aria-label={title ?? 'Authentication'}>
      {title && <h2 className="auth-container__title">{title}</h2>}
      {description && (
        <p className="auth-container__description">{description}</p>
      )}
      {children}
    </div>
  );
}

// packages/vue/src/AuthContainer.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { AuthContainerMode } from './types';

const props = withDefaults(
  defineProps<{
    mode?: AuthContainerMode;
    title?: string;
    description?: string;
    className?: string;
  }>(),
  { mode: 'credentials' },
);

const classes = computed(() =>
  [
    'auth-container',
    props.mode !== 'credentials' && `auth-container--${props.mode}`,
    props.className,
  ]
    .filter(Boolean)
    .join(' '),
);
</script>

<template>
  <div :class="classes" role="group" :aria-label="title ?? 'Authentication'">
    <h2 v-if="title" class="auth-container__title">{{ title }}</h2>
    <p v-if="description" class="auth-container__description">{{ description }}</p>
    <slot />
  </div>
</template>
